name: Python Package using Mamba

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
      
    - name: create environment with conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: conda-forge,defaults
        auto-update-conda: true
        auto-activate-base: true
    - name: Build + test
      run: |
        mkdir ~/envs
        conda env create -f environment.yml --prefix ~/envs/pele
        conda activate ~/envs/pele
        conda install libgl
        
        # test a vanilla install with no LAMMPS interface
        pip install .[testing]
        cd
        nosetests pele
        cd - 

        # test an install with a pure Python LAMMPS interface
        pip install .[lammps,testing]
        cd
        nosetests pele
        cd - 

        # test an install with a c++ LAMMPS interface
        pip install .[lammps,testing] -Csetup-args="-Dlammps=enabled"
        cd
        nosetests pele
        cd - 
